var localise = {
"Drag components from the Menu to Breadboard, then Right-Click component to edit":"Faites glisser les composants sur la plaque d'essai, puis éditez avec un clic droit",
" (For FF >= 1.5only)":" (Pour FF >= 1.5 seulement)", 
" (For IE >= 6.0only)":" (Pour IE >= 6.0 seulement)",
"menu location control":"Emplacement du menu",
"Left":"Gauche",
"Centre":"Centre",
"Right":"Droit",
"Front":"Devant",
"Back":"Derrière",
"Before printing the screen ":"Pour une impression d'écran, ",
"enable browser printing":"autoriser le navigateur à imprimer ",
" of background colours and images":" les couleurs et les images de fond",
"PEBBLE by ":"PEBBLE par ",
"Concept based on Virtual Breadboard by ":"Concept basé sur la Plaque d'Essai Virtuelle de ",
"This is a work in progress.":"Ce développement est en cours.",
"Visit the ":"Visitez ",
"for information on the PICAXE":"pour des informations sur les PICAXE",
"micro-controller chips.":"microcontrôleurs.",
"Without the top 'off-board' area":"Sans la zone hors plaque",
"With the topside 'off-board' area":"Avec la zone hors plaque en haut",
"Component Vertical Placement Control":"Commande de position verticale du composant ",
"This feature is used to adjust the vertical placement of ":"Ce dispositif est employé pour ajuster la position verticale de ",
"ALL":"tous",
" components":" les composants",
"following the Enabling or Disabling of the Top-side Off-board component area.":" active ou désactive de la zone supérieure de composants hors plaque.",
"Button selections below act by moving ":"Les boutons ci-dessous permettent le déplacement ",
" components as follows:":" des composants comme suit:",
"Use when a top side off-board area has been added to the PEBBLE display.":"Utiliser quand une zone supérieure hors plaque a été ajoutée à l'affichage de PEBBLE.",
"Use when a top side off-board area has been removed from the PEBBLE":"Utiliser quand une zone supérieure hors plaque a été supprimée de PEBBLE",
"display and you wish to delete/drop all components from the Top-side Off-board area.":"et si vous voulez supprimer tous les composants de la zone supérieure hors plaque.",
"display and you wish to gather all components from the Top-side Off-board area at":"et si vous voulez prélever tous les composants de la zone supérieure hors plaque",
"the top of the breadboard for manual repositioning.":"vers la plaque d'essai pour le placement manuel.",
"Variable Sized Strip-Board Properties":"Dimensions des différentes cartes prototype",
"This feature is only valid/functional for the Breadboard ":"Ce dispositif est seulement valide/fonctionnel pour la plaque d'essai",
"type : ":"type : ",
"'General Stripboard max 43x71'":"'La carte prototype générale maximum 43x71'",
"You can use these setting to pre-define the breadboard size":"Vous pouvez employer ces derniers arrangement pour prédéfinir la taille de la plaque d'essai",
"before selecting the General Stripboard.":"avant de choisir la carte prototype générale",
"Use the Dropdown selectors below to set the Width (Rows)":"Utilisez les sélecteurs Dropdown ci-dessous pour placer la largeur (les rangées)",
"and Height for the desired size of the General Stripboard.":"et hauteur pour la taille désirée de la carte prototype générale.",
"Board Width/Rows:":"Largeur/rangées de plaque:",
"Board Vert Height:":"Hauteur de carte:",
"Holes =":"Trous =",
"Save and Load PEBBLE Layout Data":"Enregistrer et charger les données de PEBBLE",
"To ":"Vers",
"Save":"Enregistrer",
"Load":"Charger",
"Copy and paste all text below into a text editor and save it.":"Copier coller tout le texte ci-dessous dans un éditeur de texte et le sauvegarder.",
"Paste previously saved text into this text area and click 'Load Circuit'.":"Collez le texte précédemment sauvé dans cette zone de texte et cliquez sur 'Chargez Circuit'.",
"DIP IC Properties":"Propriétés circuits DIP",
"Part # : ":"Partie # : ",
"LED Properties":"Propriétés LED",
"Select Colour : ":"Choisissez la couleur : ",
"Red":"Rouge",
"Green":"Vert",
"Yellow":"Jaune",
"Blue":"Bleu",
"White":"Blanc",
"Transistor Properties":"Propriétés Transistor",
"Type: ":"Type: ",
"Pins: ":"Broches: ",
"Package:":"Boitier: ",
"Orientation:":"Orientation:",
"Diode Properties":"Propriétés Diode",
"Image: ":"Image: ",
"Vertical":"Vertical",
"Small":"Petite",
"Medium":"Moyenne",
"Large":"Grande",
"Capacitor Properties":"Propriétés Condensateur",
"Value: ":"Valeur: ",
"Terminal Properties":"Propriétés Connecteurs",
"Terminal Type: ":"Type de Connecteur: ",
"Label: ":"Étiquette: ",
"Strip Size: ":"Taille de piste: ",
"Program Socket":"Connecteur de programmation",
"Screw Terminal":"Bornier",
"Header Socket":"Connecteur femelle",
"Header Pins":"Connecteur mâle",
"SIL Modules":"Modules SIL",
"for":"pour",
" for ":" pour ",
"Humidity":"Humidité",
"Pressure":"Pression",
"Wire Properties":"Propriétés du Câble",
"Wire Length:":"Longueur de Câble",
"Span ":"Etendue ",
"Wire Level:":"Position du Câble",
"Standard":"Standard",
"Under":"dessous",
"Above":"dessus",
"Wire Body Offset:":"Décalage du Câble :",
"On the line":"Sur la ligne",
" space above/left":" espace au-dessus/à gauche",
" space below/right":" espace au-dessous/à droite",
"Top or Left Wire End:":"Extrémité Supérieure ou Gauche de Câble:",
"Bare &":"Nu &",
"Insulated and going":"Isolé et allant",
"If insulated, then end aligns":"Si isolé, aligné",
"to hole":"sur le trou",
"up/left ":"en haut/gauche",
"straight":"droit",
"down/right":"en bas/droit",
"Bottom or Right Wire End:":"Extrémité Inférieure ou Droite du Câble:",
"Switch Properties":"Propriétés de l'Inverseur:",
"Wire Cols: ":"Couleurs de Fil:",
"Size: ":"Taille",
"Hex rotary":"Rotatif 16 pos",
" switches":" inverseurs",
"Sml Tactile Sw":"Petit Bouton-poussoir",
"Lrg Tactile Sw":"Grand Bouton-poussoir",
"Miscellaneous":"Divers",
" Device Selection":" Choix de Composants",
"Device:":"Composants:",
"LDR":"LDR",
"Thermistor":"Thermistance",
"Resonator":"Résonateur",
"Clock Crystal":"Quartz",
"Piezo Buzzer":"Vibreur piézo",
"Piezo Speaker":"Haut-parleur piézo",
"Pot - shaft left":"Potentiomètre - axe gauche",
"Pot - shaft right":"Potentiomètre - axe droite",
"TrimPot - Horiz.":"R ajust - horizontale",
"TrimPot - Vert m/t":"R ajust - verticale",
"Battery ":"Batterie ",
" End to End":" Bout à bout",
" Side by Side":" Côte à côte",
" Pushbutton":" Bouton poussoir",
" Serial":" Série",
" Parallel":" Parallèle",
" Backlight":" Rétroéclairé",
" Ultrasonic":" Ultrasonique",
" control":"commande",
" switch control:":" commande par contact:",
" Compass Module":" Module boussole",
"Motor - shaft left":"Moteur - axe à gauche",
"Motor - shaft right":"Moteur - axe à droite",
"Servo Motor":"Servo Moteur",
"Unipolar Stepper":"Pas à pas unipolaire",
"Bipolar Stepper":"Pas à pas bipolaire",
" Keypad":"Clavier",
" Relay":"Relais",
"Test Pin - 1 Hole":"connecteur de test - 1 trou",
"Test Socket - 1 Hole":"connecteur de test - 1 trou",
"2-Pin Bridge - Horizontal":"Cavalier - Horizontal",
"2-Pin Bridge - Vertical":"Cavalier - Vertical",
"Stripboard track cut":"Coupure de piste de carte proto",
"NC - No Connection Ind":"NC - Indication de non Raccordement",
" Module":" Module",
" to ":" à ",
" or ":" ou ",
" Audio-Sound":" Audio-Sons",
"Note Properties":"Notez les Propriétés",
"Text:":"Texte:",
"Note Size: ":"Taille de la note: ",
"Small Note":"Petite Note",
"Large Note":"Grande note",
"Resistor Properties":"Propriétés de Résistance",
"Resistance: ":"Résistance: ",
"Save or Load":"Sauvegarder Charger",
"Clear All":"Tout Effacer",
"Comp Up/Dn":"Comp Haut/Bas",
"Set General StripBoard":"Taille Cartes Prototype",
"Print the Screen . . .":"Impression Ecran",
"Cancel":"Abandonner",
"Load Circuit":"Charger le Circuit",
"Select All":"Tout sélectionner",
"Downwards":"En bas",
"Up & Drop":"Haut et Supprimer",
"Up & Gather":"Haut et Rassemblez", 
"Default (10 x 10)":"Par défault (10 x 10)",


"Use New Settings":"Utiliser les nouveaux réglages",
"Okay":"Ok",
"Copy":"Copier",
"Delete":"Supprimer",




"-":"-"
};